config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/courses", to: "courses#index"
  post "/courses", to: "courses#create"
  resources :users
  resources :account_activations, only: :edit
  resources :courses do
    resources :reviews
    resources :registers
  end
  resources :password_resets, except: %i(index show destroy)
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("layouts.application.title"), "#", id: "logo" %> 
    <nav>
      <ul class="nav navbar-nav navbar-right"> 
        <li><%= link_to t("static_pages.home.homepages"), root_path, class: "glyphicon glyphicon-home" %></li> 
        <li><%= link_to t("static_pages.help.helppages"), help_path, class: "glyphicon glyphicon-question-sign" %></li> 
        <li><%= link_to t("static_pages.about.aboutpages"), about_path, class: "glyphicon glyphicon-info-sign" %></li> 
        
        <% if logged_in? %>
          <li><%= link_to t("static_pages.layout.users"), users_path, class: "glyphicon glyphicon-user" %></li>
          <div class="dropdown">
            <button class="dropbtn">Account<i class="caret"></i></button>
            <div class="dropdown-content">
              <li><%= link_to t("static_pages.layout.profile"), current_user, class: "glyphicon glyphicon-education" %></li>
              <li><%= link_to t("static_pages.layout.settings"), edit_user_path(current_user), class: "glyphicon glyphicon-edit" %></li>
              <li><%= link_to t("static_pages.layout.courses"), courses_path, class: "glyphicon glyphicon-book" %></li>
              <div class="divider"></div>
              <li>
              <li><%= link_to t("static_pages.application.logout"), logout_path, class: "glyphicon glyphicon-log-out" %>
              </li>
            </div>
          </div>
        <% else %>
          <li><%= link_to t("static_pages.application.login"), login_path,class: "glyphicon glyphicon-log-in" %></li>
        <% end %>
      </ul> 
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> | <%= t "layouts.application.title" %> </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

  </head>
    <%= render "layouts/header" %>
  <body>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %> 
    </div>
  </body>
</html>